[Documents for @litert/jwt](../../index.md) / [Errors](../index.md) / JwtError

# Abstract Class: JwtError

Defined in: [src/lib/Errors.ts:22](https://github.com/litert/jwt.js/blob/master/src/lib/Errors.ts#L22)

The class representing errors in JWT module.

## Extends

- `Error`

## Extended by

- [`E_VERIFY_FAILED`](E_VERIFY_FAILED.md)
- [`E_INVALID_SETTINGS`](E_INVALID_SETTINGS.md)
- [`E_SIGN_FAILED`](E_SIGN_FAILED.md)

## Constructors

### Constructor

> **new JwtError**(`code`, `context`, `origin`): `JwtError`

Defined in: [src/lib/Errors.ts:53](https://github.com/litert/jwt.js/blob/master/src/lib/Errors.ts#L53)

#### Parameters

##### code

[`EErrorCode`](../enumerations/EErrorCode.md)

##### context

`IDict` = `{}`

##### origin

`unknown` = `null`

#### Returns

`JwtError`

#### Overrides

`Error.constructor`

## Properties

### cause?

> `optional` **cause**: `unknown`

Defined in: node\_modules/typescript/lib/lib.es2022.error.d.ts:26

#### Inherited from

`Error.cause`

***

### code

> `readonly` **code**: [`EErrorCode`](../enumerations/EErrorCode.md)

Defined in: [src/lib/Errors.ts:41](https://github.com/litert/jwt.js/blob/master/src/lib/Errors.ts#L41)

The reason code of the exception.

***

### context

> `readonly` **context**: `IDict`

Defined in: [src/lib/Errors.ts:31](https://github.com/litert/jwt.js/blob/master/src/lib/Errors.ts#L31)

Context of the exception.

> Note:
> It's not recommended to use bigint and code types as values/keys in the context,
> which is not supported by JSON serialization.

***

### message

> **message**: `string`

Defined in: node\_modules/typescript/lib/lib.es5.d.ts:1077

#### Inherited from

`Error.message`

***

### name

> **name**: `string`

Defined in: node\_modules/typescript/lib/lib.es5.d.ts:1076

#### Inherited from

`Error.name`

***

### origin

> `readonly` **origin**: `unknown`

Defined in: [src/lib/Errors.ts:36](https://github.com/litert/jwt.js/blob/master/src/lib/Errors.ts#L36)

The origin of the exception.

***

### stack?

> `optional` **stack**: `string`

Defined in: node\_modules/typescript/lib/lib.es5.d.ts:1078

#### Inherited from

`Error.stack`

***

### errorMessage

> `static` **errorMessage**: `string` = `'unknown'`

Defined in: [src/lib/Errors.ts:51](https://github.com/litert/jwt.js/blob/master/src/lib/Errors.ts#L51)

The description of the error.

***

### errorName

> `static` **errorName**: `string` = `'unknown'`

Defined in: [src/lib/Errors.ts:46](https://github.com/litert/jwt.js/blob/master/src/lib/Errors.ts#L46)

The error name.

***

### stackTraceLimit

> `static` **stackTraceLimit**: `number`

Defined in: node\_modules/@types/node/globals.d.ts:68

The `Error.stackTraceLimit` property specifies the number of stack frames
collected by a stack trace (whether generated by `new Error().stack` or
`Error.captureStackTrace(obj)`).

The default value is `10` but may be set to any valid JavaScript number. Changes
will affect any stack trace captured _after_ the value has been changed.

If set to a non-number value, or set to a negative number, stack traces will
not capture any frames.

#### Inherited from

`Error.stackTraceLimit`

## Methods

### captureStackTrace()

> `static` **captureStackTrace**(`targetObject`, `constructorOpt?`): `void`

Defined in: node\_modules/@types/node/globals.d.ts:52

Creates a `.stack` property on `targetObject`, which when accessed returns
a string representing the location in the code at which
`Error.captureStackTrace()` was called.

```js
const myObject = {};
Error.captureStackTrace(myObject);
myObject.stack;  // Similar to `new Error().stack`
```

The first line of the trace will be prefixed with
`${myObject.name}: ${myObject.message}`.

The optional `constructorOpt` argument accepts a function. If given, all frames
above `constructorOpt`, including `constructorOpt`, will be omitted from the
generated stack trace.

The `constructorOpt` argument is useful for hiding implementation
details of error generation from the user. For instance:

```js
function a() {
  b();
}

function b() {
  c();
}

function c() {
  // Create an error without stack trace to avoid calculating the stack trace twice.
  const { stackTraceLimit } = Error;
  Error.stackTraceLimit = 0;
  const error = new Error();
  Error.stackTraceLimit = stackTraceLimit;

  // Capture the stack trace above function b
  Error.captureStackTrace(error, b); // Neither function c, nor b is included in the stack trace
  throw error;
}

a();
```

#### Parameters

##### targetObject

`object`

##### constructorOpt?

`Function`

#### Returns

`void`

#### Inherited from

`Error.captureStackTrace`

***

### prepareStackTrace()

> `static` **prepareStackTrace**(`err`, `stackTraces`): `any`

Defined in: node\_modules/@types/node/globals.d.ts:56

#### Parameters

##### err

`Error`

##### stackTraces

`CallSite`[]

#### Returns

`any`

#### See

https://v8.dev/docs/stack-trace-api#customizing-stack-traces

#### Inherited from

`Error.prepareStackTrace`
